@startuml

autonumber

boundary "Wallet" as wallet
boundary "Issuer SPA" as issuerSpa
boundary "Credential Issuer" as issuerVci
boundary "Auth Server" as authOidc

issuerSpa -> issuerVci++: GET https://<domain>/credential-offers \n"Authorization":"access_token"
issuerVci -> issuerVci: Creation Credential Offer
issuerVci -> authOidc++: GET https://<domain>/grants \n"Authorization":"access_token"
authOidc -> authOidc: Generate pre-authorized_code
authOidc -> authOidc: Save the access_token \n related to the pre-authorized_code
authOidc -> issuerVci--: 200 OK Response \n{"data":"grants"}
issuerVci -> issuerVci: Credential Offer
issuerVci -> issuerVci: Save Credential Offer
issuerVci -> issuerVci: Generate credential_offer_uri
issuerVci -> issuerSpa--: 200 OK Response \n{"data":"credential_offer_uri"}
issuerSpa -> issuerSpa: Show QR code
wallet <-> issuerSpa: Scan QR code
wallet -> wallet: Execute "credential_offer_uri"
wallet -> issuerVci++: GET https://<domain>/credential-offer/{id}
issuerVci -> issuerVci: Get credential offer by ID
issuerVci -> wallet--: 200 OK \n{"data":"credential_offer"}


@enduml