package es.puig.issuer.domain.model;

import es.puig.issuer.domain.model.dto.CommitCredential;
import org.junit.jupiter.api.Test;

import java.util.Date;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;

class CommitCredentialTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        UUID expectedCredentialId = UUID.randomUUID();
        String expectedGicarId = "sampleGicarId";
        Date expectedExpirationDate = new Date();
        // Act
        CommitCredential dto = new CommitCredential(expectedCredentialId, expectedGicarId, expectedExpirationDate);
        // Assert
        assertEquals(expectedCredentialId, dto.credentialId());
        assertEquals(expectedGicarId, dto.gicarId());
        assertEquals(expectedExpirationDate, dto.expirationDate());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        UUID expectedCredentialId = UUID.randomUUID();
        String expectedGicarId = "sampleGicarId";
        Date expectedExpirationDate = new Date();
        // Act
        CommitCredential dto1 = new CommitCredential(expectedCredentialId, expectedGicarId, expectedExpirationDate);
        CommitCredential dto2 = new CommitCredential(expectedCredentialId, expectedGicarId, expectedExpirationDate);
        // Assert
        assertEquals(dto1, dto2); // Tests equals() method generated by Lombok
        assertEquals(dto1.hashCode(), dto2.hashCode()); // Tests hashCode() method generated by Lombok
    }

}
