package es.puig.issuer.domain.model;

import es.puig.issuer.domain.model.dto.CredentialDefinition;
import es.puig.issuer.domain.model.dto.CredentialRequest;
import es.puig.issuer.domain.model.dto.Proof;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

class CredentialRequestTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        String expectedFormat = "sampleFormat";
        Proof expectedProof = new Proof("jwt_vc_json", "sampleJwt");
        CredentialDefinition expectedCredentialDefinition = new CredentialDefinition(List.of("type"));
        // Act
        CredentialRequest credentialRequest = new CredentialRequest(expectedFormat, expectedCredentialDefinition, expectedProof);
        // Assert
        assertEquals(expectedFormat, credentialRequest.format());
        assertEquals(expectedProof, credentialRequest.proof());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        String expectedFormat = "sampleFormat";
        Proof expectedProof = new Proof("jwt_vc_json", "sampleJwt");
        CredentialDefinition expectedCredentialDefinition = new CredentialDefinition(List.of("type"));
        // Act
        CredentialRequest dto1 = new CredentialRequest(expectedFormat, expectedCredentialDefinition, expectedProof);
        CredentialRequest dto2 = new CredentialRequest(expectedFormat, expectedCredentialDefinition, expectedProof);
        // Assert
        assertEquals(dto1, dto2); // Tests equals() method generated by Lombok
        assertEquals(dto1.hashCode(), dto2.hashCode()); // Tests hashCode() method generated by Lombok
    }

}
