package es.puig.issuer.domain.model;

import es.puig.issuer.domain.model.dto.CredentialErrorResponse;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class CredentialErrorResponseTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        String expectedError = "sampleError";
        String expectedDescription = "sampleDescription";
        // Act
        CredentialErrorResponse responseError = new CredentialErrorResponse(expectedError, expectedDescription);
        // Assert
        assertEquals(expectedError, responseError.error());
        assertEquals(expectedDescription, responseError.description());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        String expectedError = "sampleError";
        String expectedDescription = "sampleDescription";
        // Act
        CredentialErrorResponse error1 = new CredentialErrorResponse(expectedError, expectedDescription);
        CredentialErrorResponse error2 = new CredentialErrorResponse(expectedError, expectedDescription);
        // Assert
        assertEquals(error1, error2); // Tests equals() method generated by Lombok
        assertEquals(error1.hashCode(), error2.hashCode()); // Tests hashCode() method generated by Lombok
    }

}
