package es.puig.issuer.domain.model;

import es.puig.issuer.domain.model.dto.Grant;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class GrantTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        String expectedPreAuthorizedCode = "1234";
        Grant.TxCode expectedTxCode = new Grant.TxCode(4, "numeric", "description");
        // Act
        Grant grant = new Grant(expectedPreAuthorizedCode, expectedTxCode);
        // Assert
        assertEquals(expectedPreAuthorizedCode, grant.preAuthorizedCode());
        assertEquals(expectedTxCode, grant.txCode());
    }

    @Test
    void testSetters() {
        // Arrange
        Grant grant = Grant.builder().preAuthorizedCode("5678").txCode(Grant.TxCode.builder().length(6).build()).build();
        // Assert
        assertEquals("5678", grant.preAuthorizedCode());
        assertEquals(6,grant.txCode().length());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        String expectedPreAuthorizedCode = "1234";
        Grant.TxCode expectedTxCode = new Grant.TxCode(4, "numeric", "description");
        // Act
        Grant grant1 = new Grant(expectedPreAuthorizedCode, expectedTxCode);
        Grant grant2 = new Grant(expectedPreAuthorizedCode, expectedTxCode);
        // Assert
        assertEquals(grant1, grant2); // Tests equals() method generated by Lombok
        assertEquals(grant1.hashCode(), grant2.hashCode()); // Tests hashCode() method generated by Lombok
    }

}
