package es.puig.issuer.domain.model;

import es.puig.issuer.domain.model.dto.SubjectDataResponse;
import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;

class SubjectDataResponseTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        Map<String, Map<String, String>> expectedCredentialSubjectData = new HashMap<>();
        // Add sample data to expectedCredentialSubjectData if needed
        // Act
        SubjectDataResponse dto = new SubjectDataResponse(expectedCredentialSubjectData);
        // Assert
        assertEquals(expectedCredentialSubjectData, dto.credentialSubjectData());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        Map<String, Map<String, String>> expectedCredentialSubjectData = new HashMap<>();
        // Act
        SubjectDataResponse dto1 = new SubjectDataResponse(expectedCredentialSubjectData);
        SubjectDataResponse dto2 = new SubjectDataResponse(expectedCredentialSubjectData);
        // Assert
        assertEquals(dto1, dto2); // Tests equals() method generated by Lombok
        assertEquals(dto1.hashCode(), dto2.hashCode()); // Tests hashCode() method generated by Lombok
    }

}
