package es.puig.issuer.domain.model;

import es.puig.issuer.domain.model.dto.VerifiableCredentialResponse;
import org.junit.jupiter.api.Test;


import static org.junit.jupiter.api.Assertions.assertEquals;

class VerifiableCredentialResponseTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        String transactionId= "1234";
        String expectedCredential = "LUpixVCWJk0eOt4CXQe1NXK....WZwmhmn9OQp6YxX0a2L";
        String expectedCNonce = "fGFF7UkhLA";
        int expectedCNonceExpiresIn = 35;
        // Act
        VerifiableCredentialResponse responseDTO = new VerifiableCredentialResponse(expectedCredential,transactionId ,expectedCNonce, expectedCNonceExpiresIn);
        // Assert
        assertEquals(expectedCredential, responseDTO.credential());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        String transactionId= "1234";
        String expectedCredential = "LUpixVCWJk0eOt4CXQe1NXK....WZwmhmn9OQp6YxX0a2L";
        String expectedCNonce = "fGFF7UkhLA";
        int expectedCNonceExpiresIn = 35;
        // Act
        VerifiableCredentialResponse dto1 = new VerifiableCredentialResponse(expectedCredential, transactionId,expectedCNonce, expectedCNonceExpiresIn);
        VerifiableCredentialResponse dto2 = new VerifiableCredentialResponse(expectedCredential, transactionId,expectedCNonce, expectedCNonceExpiresIn);
        // Assert
        assertEquals(dto1, dto2); // Tests equals() method generated by Lombok
        assertEquals(dto1.hashCode(), dto2.hashCode()); // Tests hashCode() method generated by Lombok
    }

}
