package es.puig.issuer.domain.model;

import es.puig.issuer.domain.model.dto.VerifiableCredential;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class VerifiableCredentialTest {

    @Test
    void testConstructorAndGetters() {
        // Arrange
        String expectedFormat = "jwt_vc_json";
        String expectedCredential = "LUpixVCWJk0eOt4CXQe1NXK....WZwmhmn9OQp6YxX0a2L";
        String expectedCNonce = "fGFF7UkhLA";
        int expectedCNonceExpiresIn = 35;
        // Act
        VerifiableCredential credentialDTO = new VerifiableCredential(
                expectedFormat,
                expectedCredential,
                expectedCNonce,
                expectedCNonceExpiresIn);
        // Assert
        assertEquals(expectedFormat, credentialDTO.format());
        assertEquals(expectedCredential, credentialDTO.credential());
        assertEquals(expectedCNonce, credentialDTO.cNonce());
        assertEquals(expectedCNonceExpiresIn, credentialDTO.cNonceExpiresIn());
    }

    @Test
    void lombokGeneratedMethodsTest() {
        // Arrange
        String expectedFormat = "jwt_vc_json";
        String expectedCredential = "LUpixVCWJk0eOt4CXQe1NXK....WZwmhmn9OQp6YxX0a2L";
        String expectedCNonce = "fGFF7UkhLA";
        int expectedCNonceExpiresIn = 35;
        // Act
        VerifiableCredential dto1 = new VerifiableCredential(
                expectedFormat,
                expectedCredential,
                expectedCNonce,
                expectedCNonceExpiresIn
        );
        VerifiableCredential dto2 = new VerifiableCredential(
                expectedFormat,
                expectedCredential,
                expectedCNonce,
                expectedCNonceExpiresIn
        );
        // Assert
        assertEquals(dto1, dto2); // Tests equals() method generated by Lombok
        assertEquals(dto1.hashCode(), dto2.hashCode()); // Tests hashCode() method generated by Lombok
    }

}
